[redis]
url = "redis://localhost:6379/?protocol=3"
channel = ""
task_queue_key = "event-queue"

[inbox]
inbox = "/home/jcake/.local/certmaster-inbox"
rescan_interval = 2

[ca]
hooks = []

certificate = "./test/authority.crt"
key = "./test/authority.key"

[web]
socket = "0.0.0.0:9999"

