name: 'certmaster'

x-common-build: &common-build
  context: .
  dockerfile: ./ca.dockerfile

services:
  public:
    image: caddy:latest
    container_name: 'public'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/config/Caddyfile
      - ./build:/www
      - ./help:/www/help
      - data:/data
    command: ["caddy", "run", "-c", "/config/Caddyfile"]
    networks:
      - certmaster

  redis:
    image: "redis:8.2-rc1-alpine3.22"
    container_name: 'certmaster-redis'
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - certmaster

  certmaster:
    build:
      <<: *common-build
      target: 'certmaster'
    container_name: 'certmaster'
    restart: unless-stopped
    entrypoint: "certmaster"
    command: ["-c", "/etc/certmaster/docker.toml"]
    environment:
      RUST_LOG: "certmaster=trace,common=trace,info"
      RUST_BACKTRACE: 1
    volumes:
      - test:/etc/certmaster
    networks:
      - certmaster

  api:
    build:
      <<: *common-build
      target: 'certmaster'
    container_name: 'api'
    restart: unless-stopped
    entrypoint: "web"
    command: ["-c", "/etc/certmaster/docker.toml"]
    environment:
      RUST_LOG: "certmaster=trace,common=trace,web=trace,info"
      RUST_BACKTRACE: 1
    ports:
      - "9999:9999"
    volumes:
      - test:/etc/certmaster
    networks:
      - certmaster

networks:
  certmaster:
    driver: bridge

volumes:
  data:
  test:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './test'